-- ============================================================
--  RestartNotifier V1.1 - A BeamMP plugin to notify players of multiple scheduled server restarts with timezone support, manual restart commands, and enhanced in-game configuration.
--  By: DeadEndReece (UkDrifter) & Help with AI (People judge, but hey, if it does what you want thats all that matters right? - Reece 2026) 
-- ============================================================

-- DO NOT EDIT THIS FILE DIRECTLY. Instead, use the in-game commands to configure restart times, timezone, and authorized users. This ensures that your settings are saved correctly and persist across server restarts.

-- Settings and state variables
local SETTINGS_PATH = "Resources/Server/RestartNotifier/time.txt" 

local AUTHORIZED_USERS = {} 

local CONFIG = {
    timezone_offset       = 0,      
    dst_active            = 0,      
    restart_times         = {{hour = 0, min = 0}}, 
    warn_start_minutes    = 5,      
    warn_interval_minutes = 1,      
    tick_ms               = 1000,
    warning_message       = "^l^bSCHEDULED ^l^cRESTART ^l^bIN ^l^c%d ^l^fMINUTE(S)",        
    seconds_warning_msg   = "^l^bSERVER ^l^cRESTART ^l^bIN ^l^c%d ^l^fSECOND(S)!",      
    final_message         = "^l^bSERVER ^l^cRESTARTING ^l^bNOW!",       
    manual_warning_msg    = "^l^bMANUAL ^l^cRESTART ^l^bIN ^l^c%d ^l^fMINUTE(S)",       
    manual_scheduled_msg  = "^l^bA MANUAL ^l^cRESTART ^l^bHAS BEEN SCHEDULED IN ^l^c%d ^l^fMINUTE(S)",      
    msg_manual_cancelled  = "^l^bMANUAL ^l^cRESTART ^l^bHAS BEEN ^l^aCANCELLED.",       
    msg_no_manual_cancel  = "^l^bNO MANUAL ^l^cRESTART ^l^bIS ACTIVE TO ^l^aCANCEL",        
    msg_no_perm_config    = "^1^cYOU DO NOT HAVE PERMISSION TO USE THAT SPECIFIC CONFIGURATION COMMAND IN-GAME.",       
    msg_no_perm_cmd       = "^c^lYOU DO NOT HAVE PERMISSION TO USE RESTART COMMANDS.",      
    msg_manual_initiated  = "^l^bMANUAL ^l^cRESTART ^l^bINITIATED.",        
    console_echo          = true, 
}


local startup_time       = os.time() 
local last_notified_min  = -1 
local last_notified_sec  = -1 
local manual_restart_at  = nil
local restart_triggered  = false 
local pending_exit_time  = nil -- NEW: Tracks when the server should actually die after the final message is sent

---- TIMEZONE MAP FOR USER-FRIENDLY DISPLAY AND INPUT ----
-- You can expand this map with more timezones as needed. 
-- The key is the timezone name (for display and user input), and the value is the offset from UTC in hours. 
-- The plugin will use this to calculate local time and display it in status messages, as well as to allow users to set their timezone using familiar names instead of just numeric offsets.
local TIMEZONE_MAP = {
    ["PST"] = -8, ["MST"] = -7, ["CST"] = -6, ["EST"] = -5,
    ["GMT"] = 0,  ["CET"] = 1,  ["EET"] = 2,  ["JST"] = 9
}

local function get_timezone_name(offset)
    for name, val in pairs(TIMEZONE_MAP) do
        if val == offset then return name end
    end
    return "Custom"
end

---- SAVE/LOAD LOGIC ----
local function save_settings()
    local f = io.open(SETTINGS_PATH, "w")
    if f then
        local users_list = {}
        for user, _ in pairs(AUTHORIZED_USERS) do
            table.insert(users_list, user)
        end
        local users_str = table.concat(users_list, ",")

        local times_list = {}
        for _, t in ipairs(CONFIG.restart_times) do
            table.insert(times_list, string.format("%02d:%02d", t.hour, t.min))
        end
        
        local times_str = table.concat(times_list, ",")
        if times_str == "" then times_str = "none" end 

        f:write(string.format("%s|%d|%d|%s", times_str, CONFIG.timezone_offset, CONFIG.dst_active, users_str))
        f:close()
        print("[RestartNotifier] Settings saved.")
    end
end

local function load_settings()
    local f = io.open(SETTINGS_PATH, "r")
    if f then
        local line = f:read("*line")
        f:close()
        if line then
            local times_str, off, dst, users = line:match("([^|]+)|(%-?%d+)|(%d+)|(.*)")
            
            if not times_str then
                times_str, off, dst = line:match("([^|]+)|(%-?%d+)|(%d+)")
                users = ""
            end

            if times_str and times_str ~= "none" then
                CONFIG.restart_times = {}
                for h, m in string.gmatch(times_str, "(%d+):(%d+)") do
                    table.insert(CONFIG.restart_times, {hour = tonumber(h), min = tonumber(m)})
                end
            else
                CONFIG.restart_times = {}
            end

            CONFIG.timezone_offset = tonumber(off)
            CONFIG.dst_active = tonumber(dst) or 0
            
            AUTHORIZED_USERS = {}
            if users and users ~= "" then
                for user in string.gmatch(users, "([^,]+)") do
                    AUTHORIZED_USERS[user] = true
                end
            end

            print(string.format("[RestartNotifier] Loaded times: %s (Zone: %s, DST: %s)", 
                (times_str == "none" and "None" or times_str), get_timezone_name(CONFIG.timezone_offset), (CONFIG.dst_active == 1 and "ON" or "OFF")))
        end
    else
        print("[RestartNotifier] No time.txt found. Building default config (00:00, GMT)...")
        CONFIG.restart_times = {{hour = 0, min = 0}}
        CONFIG.timezone_offset = 0
        CONFIG.dst_active = 0
        save_settings()
    end
end

--- UTILITY FUNCTIONS ----
local function broadcast(msg)
    if CONFIG.console_echo then print("[RestartNotifier] " .. msg) end
    MP.SendChatMessage(-1, msg)
end

local function reply(sender_id, msg)
    print("[RestartNotifier] " .. msg)
    if sender_id then
        MP.SendChatMessage(sender_id, msg)
    end
end

local function get_minutes_until_target()
    if #CONFIG.restart_times == 0 then return 999999, 0, 0 end
    
    local t_utc = os.date("!*t", os.time())
    local now_mins_utc = (t_utc.hour * 60) + t_utc.min
    local total_offset = CONFIG.timezone_offset + CONFIG.dst_active
    
    local min_diff = 1440 * 2 
    local next_hour, next_min = 0, 0

    for _, t in ipairs(CONFIG.restart_times) do
        local target_mins_utc = (t.hour * 60) + t.min - (total_offset * 60)
        
        -- OPTIMIZED: The modulo operator removes the need for a while loop
        local diff = (target_mins_utc - now_mins_utc) % 1440 
        
        if diff < min_diff then
            min_diff = diff
            next_hour = t.hour
            next_min = t.min
        end
    end
    
    return min_diff, next_hour, next_min
end

local function ProcessCommand(args, sender_id)
    local command = args[1]:lower()

    if sender_id ~= nil then
        if command ~= "restart.status" and command ~= "r.s" and
           command ~= "restart.firein" and command ~= "r.f" and
           command ~= "restart.cancel" and command ~= "r.c" and
           command ~= "restart.help"   and command ~= "r.h" and
           command ~= "restart.listtimes" and command ~= "r.lt" then
            reply(sender_id, CONFIG.msg_no_perm_config)
            return
        end
    end

    if command == "restart.help" or command == "r.h" then
        if sender_id then
            reply(sender_id, "---------- RestartNotifier (In-Game) ----------")
            reply(sender_id, "restart.status (r.s)             - Current status & countdown")
            reply(sender_id, "restart.listtimes (r.lt)         - List all scheduled times")
            reply(sender_id, "restart.firein (r.f) <mins>      - Start manual countdown")
            reply(sender_id, "restart.cancel (r.c)             - Cancel manual countdown")
            reply(sender_id, "-----------------------------------------------")
        else
            print("-------------------- RestartNotifier Commands --------------------")
            print("restart.status (r.s)             - Current status & countdown")
            print("restart.listtimes (r.lt)         - List all scheduled times")
            print("restart.addtime (r.at) HH:MM     - Add a scheduled restart time (Max 4)")
            print("restart.removetime (r.rt) HH:MM  - Remove a scheduled restart time")
            print("restart.cleartimes (r.ct)        - Clear all scheduled times")
            print("restart.settimezone (r.sz) <name>- Set timezone (EST, GMT, CET)")
            print("restart.zones (r.z)              - List available timezones")
            print("restart.dst (r.dst) <on/off>     - Toggle Daylight Saving (+1 hr)")
            print("restart.firein (r.f) <mins>      - Start manual countdown")
            print("restart.cancel (r.c)             - Cancel manual countdown")
            print("restart.adduser (r.au) <name>    - Add auth player (Console Only)")
            print("restart.removeuser (r.ru) <name> - Remove auth player (Console Only)")
            print("restart.users (r.us)             - List auth players (Console Only)")
            print("------------------------------------------------------------------")
        end

    elseif command == "restart.adduser" or command == "r.au" then
        if sender_id ~= nil then return end 
        local new_user = args[2]
        if new_user then
            AUTHORIZED_USERS[new_user] = true
            save_settings()
            print("[RestartNotifier] Added " .. new_user .. " to authorized users.")
        else
            print("[RestartNotifier] Usage: restart.adduser <name>")
        end

    elseif command == "restart.removeuser" or command == "r.ru" then
        if sender_id ~= nil then return end
        local del_user = args[2]
        if del_user then
            if AUTHORIZED_USERS[del_user] then
                AUTHORIZED_USERS[del_user] = nil
                save_settings()
                print("[RestartNotifier] Removed " .. del_user .. " from authorized users.")
            else
                print("[RestartNotifier] User " .. del_user .. " is not in the list.")
            end
        else
            print("[RestartNotifier] Usage: restart.removeuser <name>")
        end

    elseif command == "restart.users" or command == "r.us" then
        if sender_id ~= nil then return end
        print("---------- Authorized Users ----------")
        local count = 0
        for u, _ in pairs(AUTHORIZED_USERS) do
            print("- " .. u)
            count = count + 1
        end
        if count == 0 then print("No authorized users found.") end
        print("--------------------------------------")
    
    elseif command == "restart.zones" or command == "r.z" then
        print("-- Timezones --")
        local zones = {}
        for name, offset in pairs(TIMEZONE_MAP) do
            local sign = offset >= 0 and "+" or ""
            table.insert(zones, string.format("%s (UTC%s%d)", name, sign, offset))
        end
        table.sort(zones)
        for _, zone_info in ipairs(zones) do
            print(zone_info)
        end
        print("---------------")

    elseif command == "restart.dst" or command == "r.dst" then
        if args[2] == "on" then
            CONFIG.dst_active = 1
            save_settings()
            print("[RestartNotifier] Daylight Saving enabled (+1 hour applied).")
        elseif args[2] == "off" then
            CONFIG.dst_active = 0
            save_settings()
            print("[RestartNotifier] Daylight Saving disabled.")
        else
            print("[RestartNotifier] Usage: restart.dst on OR restart.dst off")
        end

    elseif command == "restart.settimezone" or command == "r.sz" then
        local input = args[2] and args[2]:upper() or ""
        local new_off = TIMEZONE_MAP[input] or tonumber(input)
        if new_off then
            CONFIG.timezone_offset = new_off
            save_settings()
            print(string.format("[RestartNotifier] Zone set to %s", get_timezone_name(new_off)))
        else
            print("[RestartNotifier] Invalid timezone.")
        end

    elseif command == "restart.addtime" or command == "r.at" then
        local h, m = (args[2] or ""):match("(%d+):(%d+)")
        if h and m then
            if #CONFIG.restart_times >= 4 then
                print("[RestartNotifier] Error: Maximum of 4 scheduled restart times allowed.")
                if sender_id then reply(sender_id, "^1^cMAXIMUM OF 4 RESTART TIMES ALLOWED.") end
            else
                table.insert(CONFIG.restart_times, {hour = tonumber(h), min = tonumber(m)})
                save_settings()
                print(string.format("[RestartNotifier] Added restart time at %02d:%02d", tonumber(h), tonumber(m)))
            end
        else
            print("[RestartNotifier] Usage: restart.addtime HH:MM")
        end

    elseif command == "restart.removetime" or command == "r.rt" then
        local h, m = (args[2] or ""):match("(%d+):(%d+)")
        if h and m then
            local removed = false
            for i, t in ipairs(CONFIG.restart_times) do
                if t.hour == tonumber(h) and t.min == tonumber(m) then
                    table.remove(CONFIG.restart_times, i)
                    removed = true
                    break
                end
            end
            if removed then
                save_settings()
                print(string.format("[RestartNotifier] Removed restart time %02d:%02d", tonumber(h), tonumber(m)))
            else
                print("[RestartNotifier] Time not found in schedule.")
            end
        else
            print("[RestartNotifier] Usage: restart.removetime HH:MM")
        end

    elseif command == "restart.cleartimes" or command == "r.ct" then
        CONFIG.restart_times = {}
        save_settings()
        print("[RestartNotifier] All scheduled restart times have been cleared.")

    elseif command == "restart.listtimes" or command == "r.lt" then
        reply(sender_id, "---------- Scheduled Times ----------")
        if #CONFIG.restart_times == 0 then
            reply(sender_id, "No scheduled restart times active.")
        else
            for _, t in ipairs(CONFIG.restart_times) do
                reply(sender_id, string.format("- %02d:%02d", t.hour, t.min))
            end
        end
        reply(sender_id, "-------------------------------------")

    elseif command == "restart.firein" or command == "r.f" then
        local mins = tonumber(args[2])
        if mins and mins >= 1 then
            manual_restart_at = os.time() + (mins * 60)
            last_notified_min = mins
            last_notified_sec = -1 
            broadcast(string.format(CONFIG.manual_scheduled_msg, mins))
            if sender_id then reply(sender_id, CONFIG.msg_manual_initiated) end
        else
            reply(sender_id, "Usage: r.f or restart.firein <minutes>")
        end

    elseif command == "restart.cancel" or command == "r.c" then
        if manual_restart_at then
            manual_restart_at = nil
            last_notified_min = -1
            last_notified_sec = -1 
            broadcast(CONFIG.msg_manual_cancelled)
        else
            reply(sender_id, CONFIG.msg_no_manual_cancel)
        end

    elseif command == "restart.status" or command == "r.s" then
        local diff, next_h, next_m = get_minutes_until_target()
        local t_utc = os.date("!*t", os.time())
        local total_offset = CONFIG.timezone_offset + CONFIG.dst_active
        local local_hr = (t_utc.hour + total_offset) % 24
        
        reply(sender_id, "---------- RestartNotifier Status ----------")
        reply(sender_id, string.format("Local Time Now   : %02d:%02d (%s%s)", 
            local_hr, t_utc.min, get_timezone_name(CONFIG.timezone_offset), (CONFIG.dst_active == 1 and "+DST" or "")))
        
        if manual_restart_at then
            local left = math.ceil((manual_restart_at - os.time()) / 60)
            reply(sender_id, string.format("MANUAL RESTART   : In %d minutes", left))
        else
            if #CONFIG.restart_times == 0 then
                reply(sender_id, "Next Scheduled   : NONE")
            else
                reply(sender_id, string.format("Next Scheduled   : %02d:%02d", next_h, next_m))
                reply(sender_id, string.format("Time Remaining   : %dh %dm", math.floor(diff / 60), diff % 60))
            end
        end
        reply(sender_id, "--------------------------------------------")
    end
end

function OnRestartTick()
    -- NEW: Check if we are in the 5-second countdown to exit
    if pending_exit_time then
        if os.time() >= pending_exit_time then
            exit()
        end
        return -- Block further restart logic while waiting to exit
    end

    if manual_restart_at then
        local secs_left = manual_restart_at - os.time()
        if secs_left <= 0 then
            if not restart_triggered then
                restart_triggered = true
                broadcast(CONFIG.final_message)
                pending_exit_time = os.time() + 5 -- Sets a non-blocking 5-second delay
            end
            return
        end
        
        if secs_left < 60 then
            local sec_bucket = math.ceil(secs_left / 10) * 10
            if sec_bucket <= 50 and sec_bucket ~= last_notified_sec and sec_bucket > 0 then
                last_notified_sec = sec_bucket
                broadcast(string.format(CONFIG.seconds_warning_msg, sec_bucket))
            end
        else
            local mins = math.ceil(secs_left / 60)
            if mins ~= last_notified_min then
                last_notified_min = mins
                broadcast(string.format(CONFIG.manual_warning_msg, mins))
            end
        end
        return 
    end

    local diff = get_minutes_until_target()
    
    if diff == 0 then
        if (os.time() - startup_time) > 90 then
            if not restart_triggered then
                restart_triggered = true
                broadcast(CONFIG.final_message)
                pending_exit_time = os.time() + 5 -- Sets a non-blocking 5-second delay
            end
        end
        return 
    elseif diff == 1 then
        local t_utc = os.date("!*t", os.time())
        local secs_left = 60 - t_utc.sec
        local sec_bucket = math.ceil(secs_left / 10) * 10
        
        if sec_bucket <= 50 and sec_bucket ~= last_notified_sec and sec_bucket > 0 then
            last_notified_sec = sec_bucket
            broadcast(string.format(CONFIG.seconds_warning_msg, sec_bucket))
        elseif sec_bucket == 60 and last_notified_min ~= 1 then
            last_notified_min = 1
            broadcast(string.format(CONFIG.warning_message, 1))
        end
    elseif diff <= CONFIG.warn_start_minutes and diff > 1 and diff ~= last_notified_min then
        last_notified_min = diff
        broadcast(string.format(CONFIG.warning_message, diff))
    end
end

function OnConsoleInput(cmd)
    local args = {}
    for word in cmd:gmatch("%S+") do table.insert(args, word) end
    if #args == 0 then return end
    
    ProcessCommand(args, nil)
end

function OnChatMessage(sender_id, sender_name, message)
    if message:sub(1, 1) == "/" then
        local cmd = message:sub(2) 
        local args = {}
        for word in cmd:gmatch("%S+") do table.insert(args, word) end
        if #args == 0 then return end
        
        local command = args[1]:lower()
        
        if command:match("^restart%.") or command:match("^r%.") then
            if AUTHORIZED_USERS[sender_name] then
                ProcessCommand(args, sender_id)
            else
                MP.SendChatMessage(sender_id, CONFIG.msg_no_perm_cmd)
            end
            
            return 1 
        end
    end
end

-- Initialization
load_settings()
MP.RegisterEvent("onConsoleInput", "OnConsoleInput")
MP.RegisterEvent("onChatMessage", "OnChatMessage") 
MP.RegisterEvent("OnRestartTick", "OnRestartTick")
MP.CreateEventTimer("OnRestartTick", CONFIG.tick_ms)